issue 3: get docker release up and running
openbao/openbao-csi-provider pull request #4
Opened 2024-05-22 15:00 UTC by jessebot

- changes .release files to reference openbao instead of hashicorp and openbao instead of vault
- fixes tests to return successfully
- updates the version of all the GHA workflow jobs

We have an empty docker repo now here:
https://quay.io/repository/openbao/openbao-csi-provider

2024-05-29 14:33 UTC, naphelps approved these changes

2024-05-29 15:18 UTC, naphelps requested changes
The makefile needs to be updated to reference v0.4.0 openbao-helm

2024-06-03 12:49 UTC, naphelps commented on .github/workflows/build.yml
> +      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
@jessebot v4 of the upload/download actions are not backwards compatible with the older v3 and so on versions. The `hashicorp/actions-docker-build@v1` integrates v3 of both and they cannot be mixed. It was one of the reasons I was looking at alternatives to get away from the Hashicorp dependency. https://github.com/openbao/openbao/pull/125

2024-07-06 19:07 UTC, JanMa approved these changes
LGTM, thanks

2024-07-06 20:02 UTC, merged

2025-04-25 15:16 UTC, eyenx commented
I don't see any images on the quay.io Docker Registry. Maybe Images are marked as private? 

I was testing today the CSI Secrets Provider and it just works, but is still using the HashiCorp Vault-CSI-Provider. I would like to put some efforts into getting releasing of openbao-csi-provider working and moving towards using this in the openbao chart.

Pinging @JanMa @cipherboy for visibility.